Added filtering to auto-configure version
TestingResearchIllinois/NonDex pull request #173
Opened 2022-08-31 11:56 UTC by kaiyaok2

Using maven filtering from source file to auto-configure version. Avoid needs to manually change versions in future upgrading.

2022-09-06 15:21 UTC, darko-marinov requested changes
Besides that space issue, the rest looks fine if you tested it.

2022-09-06 15:21 UTC, darko-marinov commented on nondex-common/pom.xml
> +	       <directory>src/main/java/edu/illinois/nondex/common</directory>
wrong indentation

2022-09-06 15:57 UTC, kaiyaok2 commented
Thanks for pointing that out! I resolved and squashed commits

Best,
Kaiyao


On Tue, Sep 6, 2022 at 11:21 PM darko-marinov ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Besides that space issue, the rest looks fine if you tested it.
> ------------------------------
>
> In nondex-common/pom.xml
> <https://urldefense.com/v3/__https://github.com/TestingResearchIllinois/NonDex/pull/173*discussion_r963843562__;Iw!!DZ3fjg!-SHThSCf_PztWASwB-K9ocUtzbD1P7LW0DNN5mC7bVBr0F7Nc_G3dvlQPYe2JrxoeDrjKBFslQ_IYYsYsRl58ckMo33Z$>
> :
>
> > @@ -13,6 +13,12 @@
>
>
>    <build>
> +    <resources>
> +       <resource>
> +	       <directory>src/main/java/edu/illinois/nondex/common</directory>
>
> wrong indentation
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/TestingResearchIllinois/NonDex/pull/173*pullrequestreview-1097793029__;Iw!!DZ3fjg!-SHThSCf_PztWASwB-K9ocUtzbD1P7LW0DNN5mC7bVBr0F7Nc_G3dvlQPYe2JrxoeDrjKBFslQ_IYYsYsRl58UT-CQmU$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ALIEJNSIR4XGB7VLHJFMH5TV45ORFANCNFSM6AAAAAAQBJWGC4__;!!DZ3fjg!-SHThSCf_PztWASwB-K9ocUtzbD1P7LW0DNN5mC7bVBr0F7Nc_G3dvlQPYe2JrxoeDrjKBFslQ_IYYsYsRl58dYJpYVC$>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-07 02:52 UTC, kaiyaok2 commented
Closing as the changes are addressed in https://github.com/TestingResearchIllinois/NonDex/pull/174

2022-09-07 02:52 UTC, closed without merging